#!/bin/bash
set -e
export PGPASSWORD=$APP_DB_PASS;
psql -v ON_ERROR_STOP=1 --username "$APP_DB_USER" --dbname "$APP_DB_NAME" <<-EOSQL
  DROP TABLE IF EXISTS reservation;
  CREATE TABLE IF NOT EXISTS reservation
  (
        id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name VARCHAR
  );
EOSQL
